# Generated by Django 5.2.17 on 2026-08-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='in_stock',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('dresses', 'Dresses'), ('abayas', 'Abayas'), ('jalabya', 'Jalabya')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(choices=[('new', 'New Collection'), ('ramadan', 'Ramadan Collection'), ('eid_fitr', 'Eid AlFitr Collection'), ('winter', 'Winter Collection'), ('eid_adha', 'Eid AlAdha Collection')], max_length=100),
        ),
    ]
