# Generated by Django 5.2.17 on 2026-08-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_productimage_image_and_more'),
        ('api', '0003_productvariant_unique_product_size'),
    ]

    operations = [
    ]
