# Generated by Django 5.2.17 on 2026-08-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20260831_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('in_process', 'In Process'), ('delivered', 'Delivered')], default='confirmed', max_length=20),
        ),
    ]
