# Generated by Django 5.2.17 on 2026-08-29 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20260827_0801'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(choices=[('new', 'New Collection'), ('ramadan', 'Ramadan Collection'), ('eid_fitr', 'Eid AlFitr Collection'), ('winter', 'Winter Collection'), ('eid_adha', 'Eid AlAdha Collection'), ('sale', 'Sale')], max_length=100),
        ),
    ]
