# Generated by Django 5.2.17 on 2026-08-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_order_is_confirmed_order_order_status'),
        ('api', '0006_alter_order_user'),
    ]

    operations = [
    ]
